// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektnaASP.Data;

#nullable disable

namespace ProjektnaASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Scifi"
                        });
                });

            modelBuilder.Entity("asp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price5")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "\"Star Wars\" is a space opera about the battle between the Jedi and the Sith. Centered around characters like Luke Skywalker and Darth Vader, the saga explores themes of family and the eternal struggle between good and evil.",
                            ImageUrl = "",
                            ListPrice = 45.0,
                            Price = 45.0,
                            Price5 = 40.0,
                            Title = "Star Wars"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "\"The Hobbit\" is a fantasy novel by J.R.R. Tolkien, following the journey of Bilbo Baggins as he accompanies a group of dwarves on a quest to reclaim their homeland. Filled with magical creatures, epic adventures, and the discovery of a powerful ring, the story sets the stage for the events of \"The Lord of the Rings\" trilogy.",
                            ImageUrl = "",
                            ListPrice = 40.0,
                            Price = 40.0,
                            Price5 = 35.0,
                            Title = "Hobbit"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "\r\n\"Indiana Jones\" is an action-adventure film series created by George Lucas and Steven Spielberg. The stories follow the adventures of Dr. Indiana Jones, an archaeologist and professor, as he travels the globe in pursuit of mystical artifacts. Known for its thrilling action sequences and iconic character, the franchise captures the essence of classic adventure storytelling",
                            ImageUrl = "",
                            ListPrice = 55.0,
                            Price = 55.0,
                            Price5 = 50.0,
                            Title = "Vanish in the Sunset"
                        });
                });

            modelBuilder.Entity("asp.Models.Product", b =>
                {
                    b.HasOne("asp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
